Repository CatDesignProject/CUKZ-BE, pull requests merged in 2024-06, with the labels that each got.

#71 Refactor(demandForm) : DemandOption - Option 연관 관계 삭제
  src/main/java/com/example/demandForm/dto/request/FormOptionRequestDto.java
  src/main/java/com/example/demandForm/dto/response/FormOptionResponseDto.java
  src/main/java/com/example/demandForm/entity/DemandOption.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
Labels: refactor

#70 feat: [#10] 총대 신청용 이메일 인증 구현
  build.gradle
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/common/jwt/JwtTokenizer.java
  src/main/java/com/example/common/mail/CustomMailSender.java
  src/main/java/com/example/common/mail/MailType.java
  src/main/java/com/example/member/controller/MemberController.java
  src/main/java/com/example/member/dto/VerifyMailDto.java
  src/main/java/com/example/member/entity/Member.java
  src/main/java/com/example/member/service/MemberVerifyMailService.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/templates/email-verification-complete.html
  src/main/resources/templates/verify-email.html
  src/test/java/com/example/common/jwt/JwtTokenizerTest.java
Labels: feat

#73 other : 상품 상세 조회 API 구매 이력 여부 반환값 추가
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/purchaseForm/repository/PurchaseFormRepository.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: other

#76 CUKZ V.0.0.7 배포
  src/main/java/com/example/security/SecurityConfig.java
Labels: bugfix

#77 feat(demandForm) : 수요조사 참여 인원 count API 구현
  src/main/java/com/example/demandForm/controller/DemandFormController.java
  src/main/java/com/example/demandForm/dto/request/FormOptionRequestDto.java
  src/main/java/com/example/demandForm/dto/response/FormOptionResponseDto.java
  src/main/java/com/example/demandForm/entity/DemandOption.java
  src/main/java/com/example/demandForm/repository/DemandOptionRepository.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
  src/test/java/com/example/demandForm/DemandTestBuilder.java
Labels: feat

#80 refactor(purchaseForm) : responseDto 수정
  src/main/java/com/example/purchaseForm/dto/PurchaseFormResponseDto.java
Labels: refactor

#82 other : isBuy 관련 로직 수정
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/purchaseForm/repository/PurchaseFormRepository.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: other

#83 CUKZ V 0.1.2 배포
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/purchaseForm/repository/PurchaseFormRepository.java
  src/main/java/com/example/purchaseForm/service/PurchaseFormService.java
  src/main/resources/application.yml
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: bugfix

#89 feat(purchaseForm) : 구매 폼 입금 상태 변경 API 로직 변경
  src/main/java/com/example/purchaseForm/controller/PurchaseFormController.java
  src/main/java/com/example/purchaseForm/dto/PayRequestDto.java
  src/main/java/com/example/purchaseForm/dto/PurchaseFormRequestDto.java
  src/main/java/com/example/purchaseForm/dto/PurchaseFormResponseDto.java
  src/main/java/com/example/purchaseForm/entity/PurchaseForm.java
  src/main/java/com/example/purchaseForm/service/PurchaseFormService.java
  src/test/java/com/example/purchaseForm/service/PurchaseFormServiceTest.java
Labels: feat

#91 refactor(purchaseForm) : responseDto seller 정보 추가
  src/main/java/com/example/purchaseForm/dto/PurchaseFormResponseDto.java
Labels: refactor

#92 refactor(purchaseForm) : responseDto seller 정보 추가
  src/main/java/com/example/purchaseForm/dto/PurchaseFormResponseDto.java
Labels: refactor

#88 feat : 상품 SaleStatus 자동 변경 스케줄러 구현
  src/main/java/com/example/CukzApplication.java
  src/main/java/com/example/common/scheduler/StatusScheduler.java
  src/main/java/com/example/product/repository/ProductRepository.java
Labels: feat
