Repository CatDesignProject/CUKZ-BE, pull requests merged in 2024-04, with the labels that each got.

#31 bugfix: [#30] dev 코드 오류 수정
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
  src/test/java/com/example/product/TestBuilder.java
Labels: bugfix

#32 feat: [#6] 중복 아이디 검증 응답 DTO 수정, 요청 DTO 유효성 검증 적용
  src/main/java/com/example/member/controller/MemberController.java
  src/main/java/com/example/member/dto/VerifyUsernameDto.java
  src/main/java/com/example/member/service/MemberService.java
Labels: feat

#33 feat: [#11] Validation DTO 검증오류 필드 모두 반환하도록 추가
  src/main/java/com/example/common/exception/ExceptionResponseDto.java
  src/main/java/com/example/common/exception/GlobalExceptionController.java
  src/main/java/com/example/common/exception/ValidationErrorResponseDto.java
Labels: feat

#34 feat: [#20] 로그아웃 구현
  src/main/java/com/example/security/SecurityConfig.java
  src/main/java/com/example/security/authentication/CustomLogoutSuccessHandler.java
Labels: feat

#36 refactor: [#35] ProductResponseDto클래스의 toResponseDto메서드 파라미터 변경
  src/main/java/com/example/product/dto/ProductOptionDto.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/product/entity/Option.java
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: refactor

#38 feat: [#37] 리뷰 작성 API
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/product/entity/Option.java
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/enums/SaleStatus.java
  src/main/java/com/example/purchaseForm/entity/PurchaseForm.java
  src/main/java/com/example/purchaseForm/repository/PurchaseFormRepository.java
  src/main/java/com/example/review/controller/ReviewController.java
  src/main/java/com/example/review/dto/request/ReviewRequestDto.java
  src/main/java/com/example/review/entity/Review.java
  src/main/java/com/example/review/repository/ReviewRepository.java
  src/main/java/com/example/review/service/ReviewService.java
  src/test/java/com/example/product/ProductTestBuilder.java
  src/test/java/com/example/product/service/ProductServiceTest.java
  src/test/java/com/example/review/ReviewTestBuilder.java
  src/test/java/com/example/review/service/ReviewServiceTest.java
Labels: test, feat, code-style

#40 refactor : [#3] 상품 옵션 변경에 따른 수요조사 폼 로직 변경
  src/main/java/com/example/common/config/JpaAuditingConfig.java
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/common/time/TimeStamp.java
  src/main/java/com/example/demandForm/controller/DemandFormController.java
  src/main/java/com/example/demandForm/dto/request/CreateDemandFormRequestDto.java
  src/main/java/com/example/demandForm/dto/request/DemandFormNonMemberRequestDto.java
  src/main/java/com/example/demandForm/dto/request/FormOptionRequestDto.java
  src/main/java/com/example/demandForm/dto/request/UpdateDemandFormRequestDto.java
  src/main/java/com/example/demandForm/dto/response/DemandFormResponseDto.java
  src/main/java/com/example/demandForm/dto/response/FormOptionResponseDto.java
  src/main/java/com/example/demandForm/entity/DemandForm.java
  src/main/java/com/example/demandForm/entity/DemandOption.java
  src/main/java/com/example/demandForm/repository/DemandFormRepository.java
  src/main/java/com/example/demandForm/repository/DemandOptionRepository.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
  src/main/java/com/example/product/entity/Option.java
  src/main/java/com/example/review/service/ReviewService.java
  src/main/resources/application.yml
  src/test/java/com/example/demandForm/DemandTest.java
  src/test/java/com/example/demandForm/DemandTestBuilder.java
  src/test/java/com/example/demandForm/service/DemandFormServiceTest.java
  src/test/java/com/example/member/entity/MemberTest.java
  src/test/java/com/example/product/ProductTestBuilder.java
Labels: feat, refactor

#43 feat: [#42] 리뷰 조회 API
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/review/controller/ReviewController.java
  src/main/java/com/example/review/dto/response/ReviewResponseDto.java
  src/main/java/com/example/review/repository/ReviewRepository.java
  src/main/java/com/example/review/service/ReviewService.java
  src/test/java/com/example/review/service/ReviewServiceTest.java
Labels: test, feat, other

#46 feat : 상품 상태, 기간 수정 API 구현
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/demandForm/controller/DemandFormController.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/dto/request/ProductFormRequestDto.java
  src/main/java/com/example/product/dto/request/ProductRequestDto.java
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
Labels: feat
