Repository CatDesignProject/CUKZ-BE, pull requests merged in 2024-05, with the labels that each got.

#47 feat : [#5] 구매폼 API 구현
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/demandForm/controller/DemandFormController.java
  src/main/java/com/example/demandForm/dto/request/DemandFormRequestDto.java
  src/main/java/com/example/demandForm/dto/request/GetFormNonMemberRequestDto.java
  src/main/java/com/example/demandForm/dto/request/ProductDemandRequestDto.java
  src/main/java/com/example/demandForm/dto/request/UpdateDemandFormRequestDto.java
  src/main/java/com/example/demandForm/dto/response/FormOptionResponseDto.java
  src/main/java/com/example/demandForm/entity/DemandForm.java
  src/main/java/com/example/demandForm/repository/DemandFormRepository.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/entity/Option.java
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/purchaseForm/controller/PurchaseFormController.java
  src/main/java/com/example/purchaseForm/dto/DeliveryRequestDto.java
  src/main/java/com/example/purchaseForm/dto/PayRequestDto.java
  src/main/java/com/example/purchaseForm/dto/ProductPurchaseRequestDto.java
  src/main/java/com/example/purchaseForm/dto/PurchaseFormRequestDto.java
  src/main/java/com/example/purchaseForm/dto/PurchaseFormResponseDto.java
  src/main/java/com/example/purchaseForm/entity/Delivery.java
  src/main/java/com/example/purchaseForm/entity/PurchaseForm.java
  src/main/java/com/example/purchaseForm/entity/PurchaseOption.java
  src/main/java/com/example/purchaseForm/repository/DeliveryRepository.java
  src/main/java/com/example/purchaseForm/repository/PurchaseFormRepository.java
  src/main/java/com/example/purchaseForm/repository/PurchaseOptionRepository.java
  src/main/java/com/example/purchaseForm/service/PurchaseFormService.java
  src/main/java/com/example/review/service/ReviewService.java
  src/test/java/com/example/demandForm/DemandTestBuilder.java
  src/test/java/com/example/demandForm/service/DemandFormServiceTest.java
  src/test/java/com/example/product/ProductTestBuilder.java
  src/test/java/com/example/purchaseForm/PurchaseTest.java
  src/test/java/com/example/purchaseForm/PurchaseTestBuilder.java
  src/test/java/com/example/purchaseForm/service/PurchaseFormServiceTest.java
  src/test/java/com/example/review/ReviewTestBuilder.java
  src/test/java/com/example/review/service/ReviewServiceTest.java
Labels: test, feat, refactor

#48 refactor : toEntity 메서드 위치 변경
  src/main/java/com/example/demandForm/dto/request/DemandFormRequestDto.java
  src/main/java/com/example/demandForm/dto/request/FormOptionRequestDto.java
  src/main/java/com/example/demandForm/entity/DemandForm.java
  src/main/java/com/example/demandForm/entity/DemandOption.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
  src/main/java/com/example/purchaseForm/dto/DeliveryRequestDto.java
  src/main/java/com/example/purchaseForm/dto/PurchaseFormRequestDto.java
  src/main/java/com/example/purchaseForm/entity/Delivery.java
  src/main/java/com/example/purchaseForm/entity/PurchaseForm.java
  src/main/java/com/example/purchaseForm/entity/PurchaseOption.java
  src/main/java/com/example/purchaseForm/service/PurchaseFormService.java
  src/test/java/com/example/demandForm/DemandTestBuilder.java
  src/test/java/com/example/demandForm/service/DemandFormServiceTest.java
  src/test/java/com/example/purchaseForm/PurchaseTestBuilder.java
  src/test/java/com/example/purchaseForm/service/PurchaseFormServiceTest.java
Labels: refactor

#49 other: S3Config 경로 수정, 상품 목록 조회 시 반환 값에 상품 id값 추가
  src/main/java/com/example/common/config/s3/S3Config.java
  src/main/java/com/example/product/dto/response/ProductThumbNailDto.java
  src/main/java/com/example/product/service/ProductService.java
Labels: other

#50 refactor : [#26] LikeResponseDto 변경
  src/main/java/com/example/likes/controller/LikesController.java
  src/main/java/com/example/likes/dto/LikesResponseDto.java
  src/main/java/com/example/likes/service/LikesService.java
  src/main/java/com/example/product/entity/Product.java
  src/test/java/com/example/likes/service/LikesServiceTest.java
Labels: refactor

#51 cicd: jasypt 암호화 적용 및 yml 파일 수정
  .github/workflows/ci.yml
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/com/example/common/config/JasyptConfig.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: bugfix, cicd

#53 other: 상품 단건 조회 응답 dto에 isLiked 필드 추가
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/product/service/ProductService.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: other

#54 fix(likes) : Response 수정
  src/main/java/com/example/common/exception/GlobalExceptionController.java
  src/main/java/com/example/likes/controller/LikesController.java
  src/main/java/com/example/likes/service/LikesService.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
Labels: feat, refactor

#56 other: ProductResponseDto, ProductThumbNailDto 필드 추가 , 컨트롤러 BaseResponse 삭제
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/product/dto/response/ProductThumbNailDto.java
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/product_image/controller/ProductImageController.java
  src/main/java/com/example/review/controller/ReviewController.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: other

#58 feat: [#19] 권한 별 api 인가 구현
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/member/controller/MemberController.java
  src/main/java/com/example/member/dto/MemberResponseDto.java
  src/main/java/com/example/member/entity/MemberRole.java
  src/main/java/com/example/member/service/MemberService.java
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/security/SecurityConfig.java
  src/main/java/com/example/security/authentication/CustomAuthenticationFailureHandler.java
  src/main/java/com/example/security/authentication/CustomAuthenticationSuccessHandler.java
  src/main/java/com/example/security/authentication/CustomLogoutSuccessHandler.java
  src/main/java/com/example/security/authentication/MemberAuthenticationToken.java
  src/main/java/com/example/security/authority/CustomAuthorityUtils.java
  src/test/java/com/example/product/service/ProductServiceTest.java
  src/test/java/com/example/review/service/ReviewServiceTest.java
Labels: bugfix, feat

#59 other : 상품 등록 시 총대 계좌 추가, 상품 상세 조회 시 옵션의 pk값 추가 반환
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/dto/ProductOptionDto.java
  src/main/java/com/example/product/dto/request/ProductRequestDto.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/review/controller/ReviewController.java
  src/test/java/com/example/product/ProductTestBuilder.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: other

#60 CUKZ V.0.0.3 배포
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/common/exception/GlobalExceptionController.java
  src/main/java/com/example/demandForm/controller/DemandFormController.java
  src/main/java/com/example/likes/controller/LikesController.java
  src/main/java/com/example/likes/service/LikesService.java
  src/main/java/com/example/member/controller/MemberController.java
  src/main/java/com/example/member/dto/MemberResponseDto.java
  src/main/java/com/example/member/entity/MemberRole.java
  src/main/java/com/example/member/service/MemberService.java
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/dto/ProductOptionDto.java
  src/main/java/com/example/product/dto/request/ProductRequestDto.java
  src/main/java/com/example/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/product/dto/response/ProductThumbNailDto.java
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/product_image/controller/ProductImageController.java
  src/main/java/com/example/purchaseForm/controller/PurchaseFormController.java
  src/main/java/com/example/review/controller/ReviewController.java
  src/main/java/com/example/security/SecurityConfig.java
  src/main/java/com/example/security/authentication/CustomAuthenticationFailureHandler.java
  src/main/java/com/example/security/authentication/CustomAuthenticationSuccessHandler.java
  src/main/java/com/example/security/authentication/CustomLogoutSuccessHandler.java
  src/main/java/com/example/security/authentication/MemberAuthenticationToken.java
  src/main/java/com/example/security/authority/CustomAuthorityUtils.java
  src/test/java/com/example/product/ProductTestBuilder.java
  src/test/java/com/example/product/service/ProductServiceTest.java
  src/test/java/com/example/review/service/ReviewServiceTest.java
Labels: cicd

#62 feat : [#61] 상품 수정 API - 이미지 수정 로직 추가
  src/main/java/com/example/product/entity/Product.java
  src/main/java/com/example/product/service/ProductService.java
  src/main/java/com/example/product_image/entity/ProductImage.java
  src/main/java/com/example/product_image/repository/ProductImageRepository.java
  src/test/java/com/example/product/ProductTestBuilder.java
  src/test/java/com/example/product/service/ProductServiceTest.java
Labels: feat

#64 feat : 내가 등록한 상품 목록 API
  src/main/java/com/example/product/controller/ProductController.java
  src/main/java/com/example/product/repository/ProductRepository.java
  src/main/java/com/example/product/service/ProductService.java
Labels: feat

#63 bugfix, refactor(demandForm) : 중복 참여 검증 로직 변경, responsedto 항목 추가
  src/main/java/com/example/common/exception/BaseErrorCode.java
  src/main/java/com/example/demandForm/dto/response/DemandFormResponseDto.java
  src/main/java/com/example/demandForm/dto/response/FormOptionResponseDto.java
  src/main/java/com/example/demandForm/repository/DemandFormRepository.java
  src/main/java/com/example/demandForm/service/DemandFormService.java
  src/test/java/com/example/demandForm/service/DemandFormServiceTest.java
Labels: bugfix, refactor

#67 hotfix(demandForm) : getAllDemandForms 상태 코드 변경
  src/main/java/com/example/demandForm/controller/DemandFormController.java
Labels: bugfix
